### ISSUE TITLE
About process raw feature

### ISSUE THREAD

**Issue by LiuDong777** [zhegan27/SCN_for_video_captioning#10]
hi zhegan
  When I extracted the C3D feature,It is a binary file (.pool5) How can I turn it into a mat file to use in the experiment. Can you give me some advice?

  thank you for your patience！

**Comment by zhegan27** [comment]
hi dong798, sorry that I have also forgotten the details, because my labmate helped me do this. That's the reason why I did not reply you in time.  Hope you have already figured it out by yourself. :)

**Comment by LiuDong777** [comment]
one more question: when i run the script python SCN_evaluation.py I get the error:
Traceback (most recent call last):
  File "SCN_evaluation.py", line 51, in <module>
    print score(refs, hypo)
  File "SCN_evaluation.py", line 25, in score
    (Meteor(),"METEOR"),
  File "/home/ld/test/SCN_for_video_captioning-master/pycocoevalcap/meteor/meteor.py", line 24, in __init__
    stderr=subprocess.PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

Could you tell me  what the reason is?

**Comment by zhegan27** [comment]
I did not meet this problem before. From what you provide, it seems difficult to identify what the problem is. I guess it is some configuration issue? Not sure about it.
