### ISSUE TITLE
OSError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by sanket7783** [zhegan27/SCN_for_video_captioning#11]
Traceback (most recent call last):
  File "SCN_evaluation.py", line 52, in <module>
    print score(refs, hypo)
  File "SCN_evaluation.py", line 25, in score
    (Meteor(),"METEOR"),
  File "/root/SCN_for_video_captioning/pycocoevalcap/meteor/meteor.py", line 24, in __init__
    stderr=subprocess.PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

**Comment by jyleehe** [comment]
Install java jre.
