### ISSUE TITLE
problems running SCN_training.py

### ISSUE THREAD

**Issue by Blues5** [zhegan27/SCN_for_video_captioning#2]
ImportError: No module named version
^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@Traceback (most recent call last):
  File "SCN_training.py", line 243, in <module>
    n_words=n_words)
  File "SCN_training.py", line 137, in train_model
    cost = f_grad_shared(x, mask,y,z)
  File "/home/koeldc23/anaconda2/envs/theano/lib/python2.7/site-packages/theano/compile/function_module.py", line 917, in __call__
    storage_map=getattr(self.fn, 'storage_map', None))
  File "/home/koeldc23/anaconda2/envs/theano/lib/python2.7/site-packages/theano/gof/link.py", line 325, in raise_with_op
    reraise(exc_type, exc_value, exc_trace)
  File "/home/koeldc23/anaconda2/envs/theano/lib/python2.7/site-packages/theano/compile/function_module.py", line 903, in __call__
    self.fn() if output_subset is None else\
  File "pygpu/gpuarray.pyx", line 693, in pygpu.gpuarray.pygpu_empty
  File "pygpu/gpuarray.pyx", line 301, in pygpu.gpuarray.array_empty
pygpu.gpuarray.GpuArrayException: cuMemAlloc: CUDA_ERROR_OUT_OF_MEMORY: out of memory
Apply node that caused the error: GpuSoftmaxWithBias(GpuDot22.0, bhid)
Toposort index: 449
Inputs types: [GpuArrayType<None>(float32, matrix), GpuArrayType<None>(float32, vector)]
Inputs shapes: [(2944, 12594), (12594,)]
Inputs strides: [(50376, 4), (4,)]
Inputs values: ['not shown', 'not shown']
Outputs clients: [[GpuAdvancedSubtensor(GpuSoftmaxWithBias.0, ARange{dtype='int64'}.0, HostFromGpu(gpuarray).0), HostFromGpu(gpuarray)(GpuSoftmaxWithBias.0)]]

Backtrace when the node is created(use Theano flag traceback.limit=N to make it longer):
  File "SCN_training.py", line 243, in <module>
    n_words=n_words)
  File "SCN_training.py", line 104, in train_model
    (use_noise, x, mask, y, z, cost) = build_model(tparams,options)
  File "/home/koeldc23/SCN_for_video_captioning/model_scn_v2/video_cap.py", line 91, in build_model
    pred = tensor.nnet.softmax(pred_x)

HINT: Use the Theano flag 'exception_verbosity=high' for a debugprint and storage map footprint of this apply node.

**Comment by Blues5** [comment]
one more question: I want to start training the models on this dataset with different captions from the scratch. How to go about that?

**Comment by jinjinyuan** [comment]
could you release the programe of predict semantic genarator attributes

**Comment by zhegan27** [comment]
Sorry for my late responses. Hope it still helps your research.

For Blues5:

1. I am not sure why the code cannot run on your machine. Maybe you have already fixed the problem.
2. How to start training from scratch? For ResNet feature and C3D feature extraction, please refer to other resources. For tag features, I have included the code for training video tagger and pretrained model. I have also included how to preprocess the raw captions file of the Youtube2Text dataset into the format used in the code in the new folder ./video_tagging. 

For jinjinyuan, 

The video tagging code and trained model is included in the github now. Please have a check.

Thanks for your interest in our work.

Best,
Zhe
